"""schema flow audit

Revision ID: 6364b785ac4e
Revises:
Create Date: 2026-06-20 05:05:49.278234+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6364b785ac4e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tenant-scoped tables that must enforce RLS. `users` is the identity table,
# queried pre-tenant, so it stays out.
RLS_TABLES: tuple[str, ...] = (
    "organizations",
    "projects",
    "agents",
    "uploads",
    "conversations",
    "messages",
    "evaluations",
    "flows",
    "audits",
    "audit_conversations",
    "message_evaluations",
    "improvements",
    "improvement_conversations",
)

_HAS_PROJECT_COL = {
    "projects",
    "agents",
    "uploads",
    "conversations",
    "messages",
    "evaluations",
    "flows",
    "audits",
    "audit_conversations",
    "message_evaluations",
    "improvements",
    "improvement_conversations",
}


def _enable_rls(table: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    if table == "organizations":
        op.execute(
            "CREATE POLICY org_isolation ON organizations "
            "USING (id = current_setting('app.current_org', true)::uuid)"
        )
        return
    op.execute(
        f"CREATE POLICY org_isolation ON {table} "
        "USING (org_id = current_setting('app.current_org', true)::uuid)"
    )
    if table in _HAS_PROJECT_COL:
        project_col = "id" if table == "projects" else "project_id"
        op.execute(
            f"CREATE POLICY project_visibility ON {table} "
            f"USING ({project_col} = ANY("
            "    string_to_array("
            "        current_setting('app.allowed_projects', true), ','"
            "    )::uuid[]"
            "))"
        )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("org_type", sa.String(length=16), nullable=False, server_default=sa.text("'customer'")),
        sa.Column("plan", sa.String(length=32), nullable=False, server_default=sa.text("'free'")),
        sa.Column(
            "white_label_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "org_type IN ('customer','agency')",
            name=op.f("ck_organizations_org_type_enum"),
        ),
        sa.CheckConstraint(
            "plan IN ('free','starter','growth','business','agency','enterprise')",
            name=op.f("ck_organizations_plan_enum"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("public_id", name=op.f("uq_organizations_public_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "projects",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("environment", sa.String(length=8), nullable=False, server_default=sa.text("'live'")),
        sa.Column("retention_days", sa.Integer(), nullable=False, server_default=sa.text("30")),
        sa.Column(
            "alert_thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('live','test')", name=op.f("ck_projects_environment_enum")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_projects_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("org_id", "slug", name="uq_projects_org_id_slug"),
        sa.UniqueConstraint("public_id", name=op.f("uq_projects_public_id")),
    )
    op.create_index(
        "ix_projects_org_id_created_at",
        "projects",
        ["org_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("supabase_user_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "allowed_project_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner','admin','editor','member','viewer')",
            name=op.f("ck_users_user_role_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_users_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("public_id", name=op.f("uq_users_public_id")),
        sa.UniqueConstraint("supabase_user_id", name=op.f("uq_users_supabase_user_id")),
    )
    op.create_index("ix_users_org_id", "users", ["org_id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('wati','respondio','manychat','twilio','custom_sdk')",
            name=op.f("ck_agents_platform_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_agents_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agents_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("project_id", "slug", name="uq_agents_project_id_slug"),
        sa.UniqueConstraint("public_id", name=op.f("uq_agents_public_id")),
    )
    op.create_index(
        "ix_agents_project_id_created_at",
        "agents",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "flows",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False, server_default=sa.text("'1.0'")),
        sa.Column("flow_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "flow_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("agent_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_flows_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_flows_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flows")),
        sa.UniqueConstraint("public_id", name=op.f("uq_flows_public_id")),
    )
    op.create_index(
        "ix_flows_project_id_created_at",
        "flows",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_flows_project_id_is_active",
        "flows",
        ["project_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "audits",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("emphasis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("free_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False, server_default=sa.text("'running'")),
        sa.Column("conversation_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "report_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running','active','archived','failed')",
            name=op.f("ck_audits_audit_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_audits_flow_id_flows"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_audits_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audits_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audits")),
        sa.UniqueConstraint("public_id", name=op.f("uq_audits_public_id")),
    )
    op.create_index("ix_audits_flow_id", "audits", ["flow_id"], unique=False)
    op.create_index(
        "ix_audits_project_id_created_at",
        "audits",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "uploads",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("status", sa.String(length=16), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("rows_total", sa.Integer(), nullable=True),
        sa.Column("rows_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','failed')",
            name=op.f("ck_uploads_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_uploads_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_uploads_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_uploads_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
        sa.UniqueConstraint("public_id", name=op.f("uq_uploads_public_id")),
    )
    op.create_index(
        "ix_uploads_org_id_status", "uploads", ["org_id", "status"], unique=False
    )
    op.create_index(
        "ix_uploads_project_id_created_at",
        "uploads",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("upload_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_phone", sa.String(length=64), nullable=True),
        sa.Column("preview", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("status", sa.String(length=16), nullable=False, server_default=sa.text("'active'")),
        sa.Column("phoenix_trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('active','completed','abandoned','escalated')",
            name=op.f("ck_conversations_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_conversations_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_conversations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_conversations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_conversations_upload_id_uploads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "agent_id", "external_id", name="uq_conversations_agent_id_external_id"
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_conversations_public_id")),
    )
    op.create_index(
        "ix_conversations_project_id_agent_id_created_at",
        "conversations",
        ["project_id", "agent_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_project_id_created_at",
        "conversations",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_upload_id", "conversations", ["upload_id"], unique=False
    )
    op.create_table(
        "improvements",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("impact", sa.String(length=200), nullable=False),
        sa.Column("why", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default=sa.text("'pending'")),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected','applied','measured')",
            name=op.f("ck_improvements_improvement_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
            name=op.f("fk_improvements_audit_id_audits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_improvements_flow_id_flows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_improvements_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_improvements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_improvements")),
        sa.UniqueConstraint("public_id", name=op.f("uq_improvements_public_id")),
    )
    op.create_index(
        "ix_improvements_flow_id", "improvements", ["flow_id"], unique=False
    )
    op.create_index(
        "ix_improvements_project_id_created_at",
        "improvements",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "audit_conversations",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("included_in_report", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
            name=op.f("fk_audit_conversations_audit_id_audits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_audit_conversations_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_audit_conversations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_conversations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_conversations")),
        sa.UniqueConstraint(
            "audit_id", "conversation_id", name="uq_audit_conversations_audit_conv"
        ),
    )
    op.create_index(
        "ix_audit_conversations_audit_id",
        "audit_conversations",
        ["audit_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_conversations_conversation_id",
        "audit_conversations",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "evaluations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.Boolean(), nullable=True),
        sa.Column("satisfaction", sa.Integer(), nullable=True),
        sa.Column("tone", sa.String(length=16), nullable=True),
        sa.Column("frustration", sa.Boolean(), nullable=True),
        sa.Column("escalated", sa.Boolean(), nullable=True),
        sa.Column("efficiency", sa.Integer(), nullable=True),
        sa.Column("scope_violation", sa.Boolean(), nullable=True),
        sa.Column("topic", sa.String(length=128), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("model_used", sa.String(length=64), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("tokens_input", sa.Integer(), nullable=True),
        sa.Column("tokens_output", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("phoenix_trace_id", sa.String(length=64), nullable=True),
        sa.Column("phoenix_span_id", sa.String(length=64), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tone IS NULL OR tone IN ('positive','neutral','negative')",
            name=op.f("ck_evaluations_tone_enum"),
        ),
        sa.CheckConstraint(
            "efficiency IS NULL OR (efficiency >= 1 AND efficiency <= 5)",
            name=op.f("ck_evaluations_efficiency_range"),
        ),
        sa.CheckConstraint(
            "satisfaction IS NULL OR (satisfaction >= 1 AND satisfaction <= 5)",
            name=op.f("ck_evaluations_satisfaction_range"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)",
            name=op.f("ck_evaluations_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_evaluations_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_evaluations_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_evaluations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evaluations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
        sa.UniqueConstraint(
            "conversation_id", name=op.f("uq_evaluations_conversation_id")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_evaluations_public_id")),
    )
    op.create_index(
        "ix_evaluations_agent_id_topic",
        "evaluations",
        ["agent_id", "topic"],
        unique=False,
    )
    op.create_index(
        "ix_evaluations_project_id_evaluated_at",
        "evaluations",
        ["project_id", "evaluated_at"],
        unique=False,
    )
    op.create_index(
        "ix_evaluations_project_id_score",
        "evaluations",
        ["project_id", "score"],
        unique=False,
    )
    op.create_table(
        "improvement_conversations",
        sa.Column("improvement_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_improvement_conversations_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["improvement_id"],
            ["improvements.id"],
            name=op.f("fk_improvement_conversations_improvement_id_improvements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_improvement_conversations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_improvement_conversations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_improvement_conversations")),
        sa.UniqueConstraint(
            "improvement_id",
            "conversation_id",
            name="uq_improvement_conversations_imp_conv",
        ),
    )
    op.create_index(
        "ix_improvement_conversations_improvement_id",
        "improvement_conversations",
        ["improvement_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_anonymized", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant','system')", name=op.f("ck_messages_role_enum")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_messages_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_messages_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("public_id", name=op.f("uq_messages_public_id")),
    )
    op.create_index(
        "ix_messages_conversation_id_seq",
        "messages",
        ["conversation_id", "seq"],
        unique=False,
    )
    op.create_table(
        "message_evaluations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=True),
        sa.Column("issue_type", sa.String(length=64), nullable=True),
        sa.Column("issue_subtype", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "label IS NULL OR label IN ('ok','warning','error')",
            name=op.f("ck_message_evaluations_message_eval_label_enum"),
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('baja','media','alta','critica')",
            name=op.f("ck_message_evaluations_message_eval_severity_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
            name=op.f("fk_message_evaluations_audit_id_audits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_message_evaluations_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_evaluations_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_message_evaluations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_message_evaluations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_evaluations")),
        sa.UniqueConstraint(
            "audit_id", "message_id", name="uq_message_evaluations_audit_message"
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_message_evaluations_public_id")),
    )
    op.create_index(
        "ix_message_evaluations_audit_id",
        "message_evaluations",
        ["audit_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_evaluations_conversation_id",
        "message_evaluations",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        _enable_rls(table)


def downgrade() -> None:
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS org_isolation ON {table}")
        op.execute(f"DROP POLICY IF EXISTS project_visibility ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_message_evaluations_conversation_id", table_name="message_evaluations"
    )
    op.drop_index("ix_message_evaluations_audit_id", table_name="message_evaluations")
    op.drop_table("message_evaluations")
    op.drop_index("ix_messages_conversation_id_seq", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_improvement_conversations_improvement_id",
        table_name="improvement_conversations",
    )
    op.drop_table("improvement_conversations")
    op.drop_index("ix_evaluations_project_id_score", table_name="evaluations")
    op.drop_index("ix_evaluations_project_id_evaluated_at", table_name="evaluations")
    op.drop_index("ix_evaluations_agent_id_topic", table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(
        "ix_audit_conversations_conversation_id", table_name="audit_conversations"
    )
    op.drop_index("ix_audit_conversations_audit_id", table_name="audit_conversations")
    op.drop_table("audit_conversations")
    op.drop_index("ix_improvements_project_id_created_at", table_name="improvements")
    op.drop_index("ix_improvements_flow_id", table_name="improvements")
    op.drop_table("improvements")
    op.drop_index("ix_conversations_upload_id", table_name="conversations")
    op.drop_index("ix_conversations_project_id_created_at", table_name="conversations")
    op.drop_index(
        "ix_conversations_project_id_agent_id_created_at", table_name="conversations"
    )
    op.drop_table("conversations")
    op.drop_index("ix_uploads_project_id_created_at", table_name="uploads")
    op.drop_index("ix_uploads_org_id_status", table_name="uploads")
    op.drop_table("uploads")
    op.drop_index("ix_audits_project_id_created_at", table_name="audits")
    op.drop_index("ix_audits_flow_id", table_name="audits")
    op.drop_table("audits")
    op.drop_index("ix_flows_project_id_is_active", table_name="flows")
    op.drop_index("ix_flows_project_id_created_at", table_name="flows")
    op.drop_table("flows")
    op.drop_index("ix_agents_project_id_created_at", table_name="agents")
    op.drop_table("agents")
    op.drop_index("ix_users_org_id", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_projects_org_id_created_at", table_name="projects")
    op.drop_table("projects")
    op.drop_table("organizations")
    # ### end Alembic commands ###
